In [1]:
import pandas as pd
from pathlib import Path

DATA = Path("data")

In [72]:
orders    = pd.read_csv(DATA / "fact_orders.csv", parse_dates=["order_ts"])
items     = pd.read_csv(DATA / "fact_order_items.csv")
customers = pd.read_csv(DATA / "dim_customer.csv", parse_dates=["signup_date"])

In [11]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     1500 non-null   int64
 1   customer_id  1500 non-null   int64
 2   order_ts     1500 non-null   datetime64[ns]
 3   status       1500 non-null   object
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 47.0+ KB

In [15]:
items.isna().sum()

order_item_id      0
order_id           0
product_id         0
quantity           0
unit_price         0
discount_pct     266
dtype: int64

In [16]:
customers.isna().sum()

customer_id     0
name            0
email          10
city_id         0
signup_date     0
dtype: int64

In [18]:
items.describe().round(2).loc[["count", "mean", "min", "max"]]

       order_item_id  order_id  product_id  quantity  unit_price  discount_pct
count         2643.0    2643.0     2643.00   2643.00     2643.00       2377.00
mean          1322.0     759.2       60.25      1.31      440.55          6.18
min              1.0       1.0        1.00      1.00        6.80          0.00
max           2643.0    1500.0      120.00      3.00      979.02         20.00

In [23]:
orders.status.value_counts(normalize=True)

status
completed    0.700667
shipped      0.153333
cancelled    0.100000
refunded     0.046000
Name: proportion, dtype: float64

In [26]:
orders["order_ts"].min(), orders["order_ts"].max()

(Timestamp('2025-01-01 00:25:58'), Timestamp('2025-06-29 22:17:47'))

In [29]:
orders.order_ts.dt.month.value_counts().sort_index()

order_ts
1    249
2    236
3    264
4    242
5    270
6    239
Name: count, dtype: int64

In [32]:
products = pd.read_csv(DATA / "dim_product.csv")

In [34]:
orders[["order_id","status"]]

      order_id     status
0            1    shipped
1            2  completed
2            3  completed
3            4  cancelled
4            5  completed
...        ...        ...
1495      1496  completed
1496      1497  completed
1497      1498  completed
1498      1499  completed
1499      1500    shipped

[1500 rows x 2 columns]

In [38]:
mask = orders.status == "refunded"
print(f"Number of refuned orders : {mask.sum()}")
orders[mask]

Number of refuned orders : 69

      order_id  customer_id            order_ts    status
14          15           93 2025-01-14 03:24:30  refunded
19          20           71 2025-05-05 04:08:34  refunded
36          37          168 2025-06-02 00:35:49  refunded
61          62           86 2025-02-28 20:57:30  refunded
70          71           81 2025-01-04 00:58:19  refunded
...        ...          ...                 ...       ...
1394      1395          114 2025-03-26 03:00:14  refunded
1436      1437           78 2025-05-14 10:03:41  refunded
1463      1464           19 2025-04-07 09:03:39  refunded
1470      1471           71 2025-01-04 13:38:01  refunded
1492      1493           48 2025-02-17 03:56:14  refunded

[69 rows x 4 columns]

In [39]:
orders[(orders.status == "refunded") & (orders.order_ts >= "2025-05-01")]

      order_id  customer_id            order_ts    status
19          20           71 2025-05-05 04:08:34  refunded
36          37          168 2025-06-02 00:35:49  refunded
82          83          107 2025-06-28 18:03:44  refunded
292        293          116 2025-06-11 01:33:07  refunded
316        317          136 2025-05-13 14:26:03  refunded
327        328            7 2025-05-20 18:13:37  refunded
390        391            3 2025-06-26 15:55:28  refunded
402        403           81 2025-05-24 02:03:34  refunded
414        415          177 2025-05-11 20:09:00  refunded
466        467          189 2025-05-30 04:45:47  refunded
477        478           89 2025-06-02 01:38:31  refunded
543        544          190 2025-05-09 09:17:40  refunded
633        634          190 2025-05-16 02:41:28  refunded
643        644           70 2025-06-11 03:35:15  refunded
678        679          114 2025-05-23 07:05:15  refunded
732        733          172 2025-05-24 18:38:59  refunded
857        858           70 2025-05-26 15:14:32  refunded
947        948          125 2025-06-20 16:55:48  refunded
986        987          172 2025-06-13 11:35:06  refunded
1018      1019          128 2025-05-28 06:23:32  refunded
1194      1195            1 2025-05-13 11:11:53  refunded
1353      1354          146 2025-05-23 17:23:09  refunded
1372      1373           10 2025-06-03 06:36:01  refunded
1436      1437           78 2025-05-14 10:03:41  refunded

In [40]:
orders[orders.status.isin(["refunded", "cancelled"])]

      order_id  customer_id            order_ts     status
3            4           27 2025-06-07 11:22:45  cancelled
14          15           93 2025-01-14 03:24:30   refunded
19          20           71 2025-05-05 04:08:34   refunded
26          27          111 2025-04-08 15:30:54  cancelled
36          37          168 2025-06-02 00:35:49   refunded
...        ...          ...                 ...        ...
1470      1471           71 2025-01-04 13:38:01   refunded
1482      1483           94 2025-02-14 21:46:26  cancelled
1490      1491           82 2025-05-15 20:07:21  cancelled
1491      1492           85 2025-03-17 09:48:38  cancelled
1492      1493           48 2025-02-17 03:56:14   refunded

[219 rows x 4 columns]

In [41]:
products[products.list_price.between(100, 200)]

     product_id          product_name  category_id  seller_id  list_price
8             9          Audio Mini 9            6         21      175.17
14           15       Kitchen Mini 15            7          7      123.28
29           30        Audio Ultra 30            6         14      109.42
43           44       Laptops Lite 44            5         19      188.66
44           45       Jackets Lite 45           10         18      190.41
51           52        Laptops Max 52            5          2      118.45
60           61         Phones Max 61            4         20      137.76
78           79  Furniture Classic 79            8          7      143.48
86           87          Audio Max 87            6          1      167.36
89           90       Phones Ultra 90            4         17      197.54
90           91        Kitchen Eco 91            7         11      145.88
100         101     Furniture Pro 101            8          1      187.96
103         104         Shoes Eco 104            9          6      120.62
119         120       Laptops Max 120            5          7      160.28

In [42]:
customers[customers.email.isna()]

     customer_id         name email  city_id signup_date
2              3  Noah Martin   NaN        4  2024-06-29
3              4  Quinn Brown   NaN        4  2025-05-19
31            32    Kim Lopez   NaN        6  2024-08-26
63            64  Kim Bernard   NaN       10  2025-03-13
72            73  Noah Garcia   NaN        6  2024-04-11
128          129    Chloe Roy   NaN        1  2024-07-11
143          144    Mia Smith   NaN        6  2024-05-21
176          177  Chloe Brown   NaN        7  2024-09-07
183          184    Mia Weber   NaN        2  2024-09-01
190          191    Jon Weber   NaN        7  2024-03-13

In [43]:
print(len(items[items.discount_pct != 5]))
print(len(items[items.discount_pct.notna() & (items.discount_pct != 5)]))

2243
1977

In [46]:
orders.query("status == 'refunded' and order_ts >= '2025-05-01'")[:10]

     order_id  customer_id            order_ts    status
19         20           71 2025-05-05 04:08:34  refunded
36         37          168 2025-06-02 00:35:49  refunded
82         83          107 2025-06-28 18:03:44  refunded
292       293          116 2025-06-11 01:33:07  refunded
316       317          136 2025-05-13 14:26:03  refunded
327       328            7 2025-05-20 18:13:37  refunded
390       391            3 2025-06-26 15:55:28  refunded
402       403           81 2025-05-24 02:03:34  refunded
414       415          177 2025-05-11 20:09:00  refunded
466       467          189 2025-05-30 04:45:47  refunded

In [47]:
lo, hi = 500, 600
products.query("@lo <= list_price <= @hi and category_id in [4, 5]")

     product_id      product_name  category_id  seller_id  list_price
2             3     Phones Mini 3            4         13      516.87
41           42  Laptops Ultra 42            5         21      539.45
61           62    Laptops Max 62            5         20      571.60
65           66    Phones Lite 66            4         21      587.57
93           94   Laptops Mini 94            5         25      557.97
112         113   Phones Mini 113            4         14      532.04
115         116   Laptops Pro 116            5         17      571.74

In [49]:
orders.sort_values(["status", "order_ts"], ascending=[True, False]).head(5)

      order_id  customer_id            order_ts     status
946        947           81 2025-06-29 20:03:10  cancelled
371        372          190 2025-06-29 16:09:55  cancelled
1163      1164          139 2025-06-29 11:03:55  cancelled
856        857          134 2025-06-25 14:14:58  cancelled
290        291          118 2025-06-23 05:17:35  cancelled

In [75]:
items["line_total"] = items.quantity * items.unit_price * \
      (1 - items.discount_pct.fillna(0) / 100)
print(f"Total : {items.line_total.sum()}")
items

Total : 1446133.457

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,line_total
0,1,1,99,1,473.17,10.0,425.8530
1,2,2,57,1,291.26,0.0,291.2600
2,3,3,10,3,596.95,5.0,1701.3075
3,4,3,83,1,560.17,0.0,560.1700
4,5,3,111,1,442.62,0.0,442.6200
...,...,...,...,...,...,...,...
2638,2639,1498,44,1,195.82,0.0,195.8200
2639,2640,1498,17,1,221.88,NaN,221.8800
2640,2641,1499,81,2,744.40,5.0,1414.3600
2641,2642,1499,93,1,748.45,NaN,748.4500
2642,2643,1500,103,1,11.22,0.0,11.2200

In [56]:
items2 = items.assign(
    discount = lambda d: d.discount_pct.fillna(0),
    gross    = lambda d: d.quantity * d.unit_price,
    net      = lambda d: d.gross * (1 - d.discount / 100),   # can use columns created just above
)
items2

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,line_total,discount,gross,net
0,1,1,99,1,473.17,10.0,425.8530,10.0,473.17,425.8530
1,2,2,57,1,291.26,0.0,291.2600,0.0,291.26,291.2600
2,3,3,10,3,596.95,5.0,1701.3075,5.0,1790.85,1701.3075
3,4,3,83,1,560.17,0.0,560.1700,0.0,560.17,560.1700
4,5,3,111,1,442.62,0.0,442.6200,0.0,442.62,442.6200
...,...,...,...,...,...,...,...,...,...,...
2638,2639,1498,44,1,195.82,0.0,195.8200,0.0,195.82,195.8200
2639,2640,1498,17,1,221.88,NaN,221.8800,0.0,221.88,221.8800
2640,2641,1499,81,2,744.40,5.0,1414.3600,5.0,1488.80,1414.3600
2641,2642,1499,93,1,748.45,NaN,748.4500,0.0,748.45,748.4500
2642,2643,1500,103,1,11.22,0.0,11.2200,0.0,11.22,11.2200

In [58]:
import numpy as np

products["tier"] = np.select(
    [products.list_price < 100, products.list_price < 500],   # conditions, checked in order
    ["cheap", "mid"],                                          # values for each
    default="premium")                                         # the ELSE
products.tier.value_counts()      # mid 63, premium 50, cheap 7

np.where(products.list_price > 500, "high", "low")            # simple two-way IF/ELSE

products["tier2"] = pd.cut(products.list_price, bins=[0, 100, 500, np.inf],
                           labels=["cheap", "mid", "premium"], right=False)   # bins; result is a category
products

,product_id,product_name,category_id,seller_id,list_price,tier,tier2
0,1,Kitchen Ultra 1,7,9,413.87,mid,mid
1,2,Audio Mini 2,6,13,768.74,premium,premium
2,3,Phones Mini 3,4,13,516.87,premium,premium
3,4,Furniture Max 4,8,23,269.23,mid,mid
4,5,Jackets Ultra 5,10,13,250.66,mid,mid
...,...,...,...,...,...,...,...
115,116,Laptops Pro 116,5,17,571.74,premium,premium
116,117,Furniture Classic 117,8,7,815.80,premium,premium
117,118,Audio Max 118,6,24,862.61,premium,premium
118,119,Shoes Lite 119,9,5,216.46,mid,mid
119,120,Laptops Max 120,5,7,160.28,mid,mid

In [59]:
orders["is_weekend"] = orders.order_ts.dt.dayofweek >= 5        # Monday = 0
orders["month"]      = orders.order_ts.dt.to_period("M")        # e.g. 2025-05, keeps the year
orders["hour"]       = orders.order_ts.dt.hour
orders.is_weekend.mean()                                         # 0.292: mean of booleans = share of True

np.float64(0.292)

In [61]:
outcome = {"completed": "ok", "shipped": "ok", "cancelled": "lost", "refunded": "lost"}
orders["outcome"] = orders.status.map(outcome)  
orders

,order_id,customer_id,order_ts,status,is_weekend,month,hour,outcome
0,1,40,2025-05-28 14:51:36,shipped,False,2025-05,14,ok
1,2,161,2025-03-03 09:18:50,completed,False,2025-03,9,ok
2,3,116,2025-01-08 07:15:44,completed,False,2025-01,7,ok
3,4,27,2025-06-07 11:22:45,cancelled,True,2025-06,11,lost
4,5,157,2025-01-31 19:48:39,completed,False,2025-01,19,ok
...,...,...,...,...,...,...,...,...
1495,1496,176,2025-02-05 09:51:48,completed,False,2025-02,9,ok
1496,1497,55,2025-02-27 15:45:31,completed,False,2025-02,15,ok
1497,1498,83,2025-06-17 09:17:37,completed,False,2025-06,9,ok
1498,1499,173,2025-01-31 01:04:22,completed,False,2025-01,1,ok
1499,1500,103,2025-02-28 00:13:07,shipped,False,2025-02,0,ok

In [ ]:
f = lambda r: r.quantity * r.unit_price * (1 - (0 if pd.isna(r.discount_pct) else r.discount_pct) / 100)
items.apply(f, axis=1).sum()

np.float64(1446133.457)

In [70]:
orders.groupby("status").size()

status
cancelled     150
completed    1051
refunded       69
shipped       230
dtype: int64

In [73]:
items.groupby("order_id").quantity.sum()

order_id
1       1
2       1
3       5
4       1
5       3
       ..
1496    3
1497    1
1498    4
1499    3
1500    1
Name: quantity, Length: 1500, dtype: int64

In [77]:
res = items.groupby("order_id").agg(
    n_items   = ("order_item_id", "size"),
    units     = ("quantity", "sum"),
    avg_price = ("unit_price", "mean"),
    revenue   = ("line_total", "sum"),
)
res

          n_items  units   avg_price    revenue
order_id
1               1      1  473.170000   425.8530
2               1      1  291.260000   291.2600
3               3      5  533.246667  2704.0975
4               1      1  720.740000   720.7400
5               3      3  452.093333  1219.9255
...           ...    ...         ...        ...
1496            1      3  798.710000  2396.1300
1497            1      1  848.170000   848.1700
1498            3      4  405.023333  2012.4400
1499            2      3  746.425000  2162.8100
1500            1      1   11.220000    11.2200

[1500 rows x 4 columns]

In [123]:
items     = pd.read_csv(DATA / "fact_order_items.csv")
items["line_total"] = items.quantity * items.unit_price * \
    (1 - items.discount_pct.fillna(0) / 100)

In [124]:
res = items.groupby("order_id").agg(
    n_items   = ("order_item_id", "size"),
    units     = ("quantity", "sum"),
    avg_price = ("unit_price", "mean"),
    revenue   = ("line_total", "sum"),
)

In [130]:
res.sort_values(["units", "revenue"], ascending=[False, False]).head(3)

          n_items  units  avg_price   revenue
order_id
72              4      8   600.3650  5077.776
1034            4      8   517.3875  3660.638
528             3      8   415.5300  3092.290

In [188]:
orders    = pd.read_csv(DATA / "fact_orders.csv", parse_dates=["order_ts"])

In [189]:
orders["month"]      = orders.order_ts.dt.to_period("M")

In [190]:
tab = orders.groupby(["month", "status"]).size()
tab.unstack()

status   cancelled  completed  refunded  shipped
month
2025-01         26        174        13       36
2025-02         20        163        13       40
2025-03         20        191        11       42
2025-04         26        173         8       35
2025-05         32        187        15       36
2025-06         26        163         9       41

In [191]:
cnt = orders[orders.status == "completed"].groupby("customer_id").size()
cnt[cnt >= 8].sort_values(ascending=False)[:10]

customer_id
186    12
64     12
179    11
35     10
71     10
66     10
17      9
140     9
136     9
52      9
dtype: int64

In [192]:
orders["n_orders_customer"] = orders.groupby("customer_id").\
    order_id.transform("count")
orders[:10].sort_values("customer_id")

,order_id,customer_id,order_ts,status,month,n_orders_customer
3,4,27,2025-06-07 11:22:45,cancelled,2025-06,11
7,8,36,2025-01-31 02:05:48,completed,2025-01,11
0,1,40,2025-05-28 14:51:36,shipped,2025-05,9
9,10,65,2025-01-11 03:10:31,completed,2025-01,9
6,7,85,2025-06-07 21:42:56,completed,2025-06,8
8,9,94,2025-05-12 08:04:46,shipped,2025-05,11
2,3,116,2025-01-08 07:15:44,completed,2025-01,9
5,6,150,2025-05-09 20:39:23,completed,2025-05,7
4,5,157,2025-01-31 19:48:39,completed,2025-01,7
1,2,161,2025-03-03 09:18:50,completed,2025-03,10

In [193]:
orders["rn"] = orders.sort_values("order_ts", ascending=False).groupby(
    "customer_id").cumcount() + 1
orders.query("customer_id == 1").sort_values("order_ts")

,order_id,customer_id,order_ts,status,month,n_orders_customer,rn
359,360,1,2025-01-30 21:48:13,completed,2025-01,9,9
100,101,1,2025-02-11 10:36:53,completed,2025-02,9,8
1437,1438,1,2025-03-13 10:22:20,completed,2025-03,9,7
449,450,1,2025-04-29 05:09:06,completed,2025-04,9,6
1194,1195,1,2025-05-13 11:11:53,refunded,2025-05,9,5
887,888,1,2025-06-15 13:47:00,completed,2025-06,9,4
570,571,1,2025-06-17 07:52:41,cancelled,2025-06,9,3
1341,1342,1,2025-06-20 14:48:07,completed,2025-06,9,2
1173,1174,1,2025-06-23 09:32:10,completed,2025-06,9,1

In [196]:
top3 = orders.sort_values("order_ts", ascending=False).groupby(
    "customer_id").head(3).sort_values("customer_id")
top3[:10]

,order_id,customer_id,order_ts,status,month,n_orders_customer,rn
1173,1174,1,2025-06-23 09:32:10,completed,2025-06,9,1
1341,1342,1,2025-06-20 14:48:07,completed,2025-06,9,2
570,571,1,2025-06-17 07:52:41,cancelled,2025-06,9,3
114,115,2,2025-03-21 14:54:24,completed,2025-03,5,3
1466,1467,2,2025-05-15 08:09:11,shipped,2025-05,5,2
1418,1419,2,2025-05-15 22:07:56,completed,2025-05,5,1
261,262,3,2025-05-04 02:07:40,shipped,2025-05,8,3
318,319,3,2025-06-11 11:57:14,completed,2025-06,8,2
390,391,3,2025-06-26 15:55:28,refunded,2025-06,8,1
1222,1223,4,2025-06-22 12:36:37,completed,2025-06,10,2

### Working on merges / JOINs

In [202]:
cities    = pd.read_csv(DATA / "dim_city.csv")
countries = pd.read_csv(DATA / "dim_country.csv")
products  = pd.read_csv(DATA / "dim_product.csv")
cats      = pd.read_csv(DATA / "dim_category.csv")
sellers   = pd.read_csv(DATA / "dim_seller.csv")
orders    = pd.read_csv(DATA / "fact_orders.csv", parse_dates=["order_ts"])

In [203]:
m = orders.merge(customers[["customer_id", "name", "city_id"]],
                 on="customer_id", how="left", validate="many_to_one")
m.head()

   order_id  customer_id            order_ts     status         name  city_id
0         1           40 2025-05-28 14:51:36    shipped  Rosa Muller        1
1         2          161 2025-03-03 09:18:50  completed   Kim Dubois        5
2         3          116 2025-01-08 07:15:44  completed    Kim Weber        1
3         4           27 2025-06-07 11:22:45  cancelled  Rosa Garcia        6
4         5          157 2025-01-31 19:48:39  completed   Leo Dubois        9

In [210]:
x = customers.merge(orders[["customer_id"]].drop_duplicates(),
                    on="customer_id", how="left", indicator=True)
print(x._merge.value_counts())
x[x._merge == "left_only"]

_merge
both          199
left_only       1
right_only      0
Name: count, dtype: int64

,customer_id,name,email,city_id,signup_date,_merge
179,180,Farid Lopez,farid.lopez180@example.com,8,2024-08-04,left_only

In [213]:
full = (items
    .merge(orders[["order_id", "customer_id", "status"]], on="order_id",     how="left", validate="many_to_one")
    .merge(customers[["customer_id", "city_id"]],         on="customer_id",  how="left", validate="many_to_one")
    .merge(cities[["city_id", "country_id"]],             on="city_id",      how="left", validate="many_to_one")
    .merge(countries[["country_id", "country_name"]],     on="country_id",   how="left", validate="many_to_one"))
full.head()

,order_item_id,order_id,product_id,quantity,unit_price,discount_pct,line_total,customer_id,status,city_id,country_id,country_name
0,1,1,99,1,473.17,10.0,425.8530,40,shipped,1,1,France
1,2,2,57,1,291.26,0.0,291.2600,161,completed,5,3,Spain
2,3,3,10,3,596.95,5.0,1701.3075,116,completed,1,1,France
3,4,3,83,1,560.17,0.0,560.1700,116,completed,1,1,France
4,5,3,111,1,442.62,0.0,442.6200,116,completed,1,1,France

In [214]:
(full[full.status == "completed"]
     .assign(gross=lambda d: d.quantity * d.unit_price)
     .groupby("country_name").gross.sum().sort_values(ascending=False).round(2))

country_name
Canada     271834.84
Germany    213367.39
USA        212773.65
Spain      190444.97
France     174856.98
Name: gross, dtype: float64

In [218]:
pd.concat([orders.head(2), orders.tail(2)], ignore_index=True)     # stack rows: UNION ALL
customers.set_index("customer_id").join(
    orders.groupby("customer_id").size().rename("n_orders"))       # join on the index

,name,email,city_id,signup_date,n_orders
customer_id,,,,,
1,Dan Martin,dan.martin1@example.com,4,2024-06-22,9.0
2,Eva Petit,eva.petit2@example.com,9,2024-03-08,5.0
3,Noah Martin,NaN,4,2024-06-29,8.0
4,Quinn Brown,NaN,4,2025-05-19,10.0
5,Rosa Tremblay,rosa.tremblay5@example.com,10,2024-08-04,8.0
...,...,...,...,...,...
196,Quinn Petit,quinn.petit196@example.com,2,2024-08-02,10.0
197,Noah Smith,noah.smith197@example.com,9,2024-07-26,6.0
198,Ana Garcia,ana.garcia198@example.com,10,2025-03-26,7.0
199,Paul Dubois,paul.dubois199@example.com,8,2024-09-25,4.0
200,Kim Weber,kim.weber200@example.com,7,2024-12-19,3.0

### Rolling aggregates and time series

In [220]:
items     = pd.read_csv(DATA / "fact_order_items.csv")
items["line_total"] = items.quantity * items.unit_price * (1 - items.discount_pct.fillna(0) / 100)
order_rev = items.groupby("order_id").line_total.sum().rename("revenue")
o = orders.merge(order_rev, on="order_id", how="left", validate="one_to_one")
ts = o[o.status == "completed"].set_index("order_ts").sort_index()
ts

                     order_id  customer_id     status   revenue
order_ts
2025-01-01 00:25:58       992           72  completed   483.888
2025-01-01 14:06:22      1107          147  completed   290.034
2025-01-01 17:46:54       137           93  completed   243.410
2025-01-01 21:17:52       336          108  completed  1037.583
2025-01-01 23:32:22       745           70  completed   251.360
...                       ...          ...        ...       ...
2025-06-29 01:14:01       834           12  completed  2189.466
2025-06-29 08:08:05       990           88  completed   122.990
2025-06-29 10:02:54      1414           79  completed   443.970
2025-06-29 17:08:44       558          115  completed   895.807
2025-06-29 22:17:47       476           71  completed     7.090

[1051 rows x 4 columns]

In [223]:
monthly = ts.revenue.resample("MS").sum().round(2)      # MS = month start
monthly

order_ts
2025-01-01    164703.65
2025-02-01    154122.73
2025-03-01    188816.26
2025-04-01    174392.72
2025-05-01    167710.45
2025-06-01    153575.17
Freq: MS, Name: revenue, dtype: float64

In [227]:
df = pd.DataFrame({"revenue": monthly})
df["prev"]          = df.revenue.shift(1)                      # LAG(revenue)
df["delta"]         = df.revenue.diff()                        # revenue - LAG(revenue)
df["pct_change"]    = df.revenue.pct_change() * 100            # month-over-month %
df["running_total"] = df.revenue.cumsum()                      # SUM() OVER (... UNBOUNDED PRECEDING)
df["ma3"]           = df.revenue.rolling(3, min_periods=1).mean()   # 3-month moving average
df.iloc[:8,:]

,revenue,prev,delta,pct_change,running_total,ma3
order_ts,,,,,,
2025-01-01,164703.65,NaN,NaN,NaN,164703.65,164703.650000
2025-02-01,154122.73,164703.65,-10580.92,-6.424217,318826.38,159413.190000
2025-03-01,188816.26,154122.73,34693.53,22.510327,507642.64,169214.213333
2025-04-01,174392.72,188816.26,-14423.54,-7.638929,682035.36,172443.903333
2025-05-01,167710.45,174392.72,-6682.27,-3.831737,849745.81,176973.143333
2025-06-01,153575.17,167710.45,-14135.28,-8.428384,1003320.98,165226.113333

In [228]:
orders.set_index("order_ts").groupby(
    [pd.Grouper(freq="MS"), "status"]).size().unstack()

status      cancelled  completed  refunded  shipped
order_ts
2025-01-01         26        174        13       36
2025-02-01         20        163        13       40
2025-03-01         20        191        11       42
2025-04-01         26        173         8       35
2025-05-01         32        187        15       36
2025-06-01         26        163         9       41

In [235]:
import sqlite3
con = sqlite3.connect("db/marketplace.db")
events = pd.read_sql("select * from web_events", con,
                      parse_dates={"event_ts": "%Y-%m-%dT%H:%M:%SZ"})

events = events.sort_values(["user_id", "event_ts", "event_id"])
gap = events.groupby("user_id").event_ts.diff()                       # Timedelta; NaT for each user's first event
events["new"] = gap.isna() | (gap > pd.Timedelta(days=7))            # first event OR long gap
events["session_no"] = events.groupby("user_id").new.cumsum()        # running sum of booleans

sessions = events.groupby(["user_id", "session_no"]).agg(
    started  = ("event_ts", "min"),
    n_events = ("event_id", "size"),
    had_cart = ("event", lambda s: (s == "add_to_cart").any()),
)
sessions

                               started  n_events  had_cart
user_id session_no
1       1          2025-01-03 11:29:42         7      True
        2          2025-01-30 00:00:08         2     False
        3          2025-02-21 03:11:51         4     False
        4          2025-03-14 02:09:05         6      True
        5          2025-04-12 10:05:31         2      True
...                                ...       ...       ...
200     6          2025-03-16 12:14:38         3     False
        7          2025-03-27 14:21:17         9      True
        8          2025-05-01 01:57:14         2     False
        9          2025-05-08 15:20:09         4      True
        10         2025-05-24 15:21:06         1     False

[1922 rows x 3 columns]

### Reshaping

In [242]:
orders    = pd.read_csv(DATA / "fact_orders.csv", parse_dates=["order_ts"])
items     = pd.read_csv(DATA / "fact_order_items.csv")
items["line_total"] = items.quantity * items.unit_price * (
    1 - items.discount_pct.fillna(0) / 100)
order_rev = items.groupby("order_id").line_total.sum().rename("revenue")
o = orders.merge(order_rev, on="order_id", how="left", validate="one_to_one")
o["month"] = o.order_ts.dt.to_period("M")
o.head()

   order_id  customer_id            order_ts     status    revenue    month
0         1           40 2025-05-28 14:51:36    shipped   425.8530  2025-05
1         2          161 2025-03-03 09:18:50  completed   291.2600  2025-03
2         3          116 2025-01-08 07:15:44  completed  2704.0975  2025-01
3         4           27 2025-06-07 11:22:45  cancelled   720.7400  2025-06
4         5          157 2025-01-31 19:48:39  completed  1219.9255  2025-01

In [ ]:
pt = o.pivot_table(index="month", columns="status", values="revenue",
                   aggfunc="sum", fill_value=0, margins=True,
                   margins_name="Total").round(0)
pt

status   cancelled  completed  refunded   shipped      Total
month
2025-01    34328.0   164704.0   14471.0   31762.0   245265.0
2025-02    15219.0   154123.0   13830.0   36923.0   220095.0
2025-03    15500.0   188816.0   11945.0   41228.0   257489.0
2025-04    23029.0   174393.0    6004.0   37417.0   240843.0
2025-05    28321.0   167710.0   14470.0   41026.0   251527.0
2025-06    26449.0   153575.0    8650.0   42241.0   230915.0
Total     142846.0  1003321.0   69370.0  230597.0  1446133.0

In [243]:
pd.crosstab(o.month, o.status)

status   cancelled  completed  refunded  shipped
month
2025-01         26        174        13       36
2025-02         20        163        13       40
2025-03         20        191        11       42
2025-04         26        173         8       35
2025-05         32        187        15       36
2025-06         26        163         9       41

In [252]:
tab = o.groupby(["month", "status"]).size().unstack()     # groupby result -> wide
tab.stack()                                               # wide -> back to a Series with a two-level index

month    status
2025-01  cancelled     26
         completed    174
         refunded      13
         shipped       36
2025-02  cancelled     20
         completed    163
         refunded      13
         shipped       40
2025-03  cancelled     20
         completed    191
         refunded      11
         shipped       42
2025-04  cancelled     26
         completed    173
         refunded       8
         shipped       35
2025-05  cancelled     32
         completed    187
         refunded      15
         shipped       36
2025-06  cancelled     26
         completed    163
         refunded       9
         shipped       41
dtype: int64

In [253]:
long = tab.reset_index().melt(id_vars="month", var_name="status", value_name="n")
long

      month     status    n
0   2025-01  cancelled   26
1   2025-02  cancelled   20
2   2025-03  cancelled   20
3   2025-04  cancelled   26
4   2025-05  cancelled   32
5   2025-06  cancelled   26
6   2025-01  completed  174
7   2025-02  completed  163
8   2025-03  completed  191
9   2025-04  completed  173
10  2025-05  completed  187
11  2025-06  completed  163
12  2025-01   refunded   13
13  2025-02   refunded   13
14  2025-03   refunded   11
15  2025-04   refunded    8
16  2025-05   refunded   15
17  2025-06   refunded    9
18  2025-01    shipped   36
19  2025-02    shipped   40
20  2025-03    shipped   42
21  2025-04    shipped   35
22  2025-05    shipped   36
23  2025-06    shipped   41

In [254]:
import json
recs = [json.loads(line) for line in open(DATA / "payments.jsonl")]
fp = pd.json_normalize(recs)                  # columns: order_id, paid_at, method, amount, card.brand, card.last4, card
pd.json_normalize(recs, sep="_")              # card_brand, card_last4 instead of dotted names

,order_id,paid_at,method,amount,card_brand,card_last4,card
0,1,2025-05-28T15:06:36Z,transfer,425.85,amex,5295,NaN
1,2,2025-03-03T09:35:50Z,card,291.26,NaN,NaN,NaN
2,3,2025-01-08T07:35:44Z,paypal,2704.10,visa,7381,NaN
3,4,2025-06-07T11:45:45Z,paypal,720.74,amex,8564,NaN
4,5,2025-01-31T20:16:39Z,card,1219.93,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1495,1496,2025-02-05T10:16:48Z,card,2396.13,mc,2265,NaN
1496,1497,2025-02-27T16:07:31Z,paypal,848.17,NaN,NaN,NaN
1497,1498,2025-06-17T09:40:37Z,paypal,2012.44,visa,3497,NaN
1498,1499,2025-01-31T01:33:22Z,transfer,2162.81,visa,6527,NaN
1499,1500,2025-02-28T00:26:07Z,card,11.22,NaN,NaN,NaN

In [ ]:
pd.DataFrame({"order_id": [1, 2], "tags": [["a", "b"], ["c"]]}).explode("tags")      # 3 rows
o.groupby("customer_id").order_id.apply(list)        # the reverse: collect values into lists

customer_id
1      [101, 360, 450, 571, 888, 1174, 1195, 1342, 1438]
2                            [115, 507, 607, 1419, 1467]
3             [262, 319, 391, 530, 768, 790, 1292, 1447]
4      [106, 160, 313, 887, 1090, 1110, 1223, 1288, 1...
5              [200, 491, 494, 574, 746, 899, 988, 1009]
                             ...
196    [50, 156, 277, 670, 941, 1017, 1134, 1176, 144...
197                      [26, 585, 610, 964, 1310, 1321]
198                  [57, 73, 247, 408, 915, 1088, 1355]
199                               [216, 219, 1269, 1363]
200                                     [275, 875, 1013]
Name: order_id, Length: 199, dtype: object